apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "upload.fullname" . }}
  labels:
    {{- include "upload.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "upload.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "upload.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "upload.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-minio
          image: busybox:latest
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for MinIO to be ready..."
              # Extract host and port from MINIO_ENDPOINT
              MINIO_HOST_PORT=$(echo $MINIO_ENDPOINT | sed 's|.*://||')
              if echo $MINIO_HOST_PORT | grep -q ':'; then
                MINIO_HOST=$(echo $MINIO_HOST_PORT | cut -d':' -f1)
                MINIO_PORT=$(echo $MINIO_HOST_PORT | cut -d':' -f2)
              else
                MINIO_HOST=$MINIO_HOST_PORT
                MINIO_PORT=80
              fi
              echo "Minio host: ${MINIO_HOST}"
              echo "Minio port: ${MINIO_PORT}"
              until nc -z $MINIO_HOST $MINIO_PORT; do
                echo "MinIO not ready, waiting 5 seconds..."
                sleep 5
              done
              echo "MinIO is ready!"
          env:
            - name: MINIO_ENDPOINT
              value: {{ .Values.minio.endpoint }}
        - name: wait-for-mongodb
          image: busybox:latest
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for MongoDB to be ready..."
              echo "Mongo host: ${MONGO_HOST}"
              echo "Mongo port: ${MONGO_PORT}"
              until nc -z $MONGO_HOST $MONGO_PORT; do
                echo "MongoDB not ready, waiting 5 seconds..."
                sleep 5
              done
              echo "MongoDB is ready!"
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  {{- if .Values.existingConfigmap }}
                  name: {{ .Values.existingConfigmap }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: mongo_host
            - name: MONGO_PORT
              value: "27017"
        - name: wait-for-redis
          image: busybox:latest
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for Redis to be ready..."
              echo "Redis host: ${REDIS_HOST}"
              echo "Redis port: ${REDIS_PORT}"
              until nc -z $REDIS_HOST $REDIS_PORT; do
                echo "Redis not ready, waiting 5 seconds..."
                sleep 5
              done
              echo "Redis is ready!"
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  {{- if .Values.existingConfigmap }}
                  name: {{ .Values.existingConfigmap }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: redis_host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  {{- if .Values.existingConfigmap }}
                  name: {{ .Values.existingConfigmap }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: redis_port
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command:
            {{- range .Values.command }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.args }}
          args:
            {{- range .Values.args }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ include "upload.port" . }}
              protocol: TCP
          env: 
            - name: MINIO_ENDPOINT
              value: {{ .Values.minio.endpoint }}
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.existingSecret }}
                  name: {{ .Values.existingSecret }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: minio_access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.existingSecret }}
                  name: {{ .Values.existingSecret }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: minio_secret_key
            - name: MINIO_BUCKET
              valueFrom:
                configMapKeyRef:
                  {{- if .Values.existingConfigmap }}
                  name: {{ .Values.existingConfigmap }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: minio_bucket
            - name: MINIO_USE_SSL
              valueFrom:
                configMapKeyRef:
                  {{- if .Values.existingConfigmap }}
                  name: {{ .Values.existingConfigmap }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: minio_use_ssl
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  {{- if .Values.existingSecret }}
                  name: {{ .Values.existingSecret }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: mongo_url
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  {{- if .Values.existingConfigmap }}
                  name: {{ .Values.existingConfigmap }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: redis_host
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.existingSecret }}
                  name: {{ .Values.existingSecret }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: redis_password
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  {{- if .Values.existingConfigmap }}
                  name: {{ .Values.existingConfigmap }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: redis_port
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  {{- if .Values.existingConfigmap }}
                  name: {{ .Values.existingConfigmap }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: redis_db
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.existingSecret }}
                  name: {{ .Values.existingSecret }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: jwt_secret_key
            - name: JWT_ALGORITHM
              valueFrom:
                secretKeyRef:
                  {{- if .Values.existingSecret }}
                  name: {{ .Values.existingSecret }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: jwt_algorithm
            - name: UVICORN_RELOAD
              value: "false"
            - name: LOG_DEBUG
              value: {{ .Values.debug | default .Values.global.debug | quote }}
            
            - name: REDIS_MAX_CONNECTIONS
              valueFrom:
                configMapKeyRef:
                  {{- if .Values.existingConfigmap }}
                  name: {{ .Values.existingConfigmap }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: redis_max_connections
            - name: REDIS_HEALTH_CHECK_INTERVAL
              valueFrom:
                configMapKeyRef:
                  {{- if .Values.existingConfigmap }}
                  name: {{ .Values.existingConfigmap }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: redis_health_check_interval
            
            - name: MONGO_MAX_POOL_SIZE
              valueFrom:
                configMapKeyRef:
                  {{- if .Values.existingConfigmap }}
                  name: {{ .Values.existingConfigmap }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: mongo_max_pool_size
            - name: MONGO_MIN_POOL_SIZE
              valueFrom:
                configMapKeyRef:
                  {{- if .Values.existingConfigmap }}
                  name: {{ .Values.existingConfigmap }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: mongo_min_pool_size
            - name: MONGO_MAX_IDLE_TIME_MS
              valueFrom:
                configMapKeyRef:
                  {{- if .Values.existingConfigmap }}
                  name: {{ .Values.existingConfigmap }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: mongo_max_idle_time_ms
            - name: MONGO_SERVER_SELECTION_TIMEOUT_MS
              valueFrom:
                configMapKeyRef:
                  {{- if .Values.existingConfigmap }}
                  name: {{ .Values.existingConfigmap }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: mongo_server_selection_timeout_ms
            
            - name: RETRY_MAX_ATTEMPTS
              valueFrom:
                configMapKeyRef:
                  {{- if .Values.existingConfigmap }}
                  name: {{ .Values.existingConfigmap }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: retry_max_attempts
            - name: RETRY_MIN_WAIT_SECONDS
              valueFrom:
                configMapKeyRef:
                  {{- if .Values.existingConfigmap }}
                  name: {{ .Values.existingConfigmap }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: retry_min_wait_seconds
            - name: RETRY_MAX_WAIT_SECONDS
              valueFrom:
                configMapKeyRef:
                  {{- if .Values.existingConfigmap }}
                  name: {{ .Values.existingConfigmap }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: retry_max_wait_seconds
            - name: RETRY_EXPONENTIAL_MULTIPLIER
              valueFrom:
                configMapKeyRef:
                  {{- if .Values.existingConfigmap }}
                  name: {{ .Values.existingConfigmap }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: retry_exponential_multiplier
            
            - name: HEALTH_CHECK_CACHE_DURATION
              valueFrom:
                configMapKeyRef:
                  {{- if .Values.existingConfigmap }}
                  name: {{ .Values.existingConfigmap }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: health_check_cache_duration
            - name: HEALTH_CHECK_TIMEOUT_SECONDS
              valueFrom:
                configMapKeyRef:
                  {{- if .Values.existingConfigmap }}
                  name: {{ .Values.existingConfigmap }}
                  {{- else }}
                  name: {{ include "upload.fullname" . }}
                  {{- end }}
                  key: health_check_timeout_seconds
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
