{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "upload.fullname" . }}
  labels:
    {{- include "upload.labels" . | nindent 4 }}
data:
  minio_access_key: {{ .Values.minio.access_key | b64enc }}
  minio_secret_key: {{ .Values.minio.secret_key | b64enc }}
  mongo_url: {{ printf "mongodb://%s:%s@%s:%d/%s" .Values.mongodb.username .Values.mongodb.password (printf "%s-%s.%s" .Release.Name .Values.global.mongodb.nameOverride .Release.Namespace) (int .Values.mongodb.port) .Values.mongodb.database | b64enc }}
  redis_password: {{ .Values.redis.password | b64enc }}
  jwt_secret_key: {{ .Values.global.jwtAuth.secret | b64enc }}
  jwt_algorithm: {{ .Values.global.jwtAuth.algorithm | b64enc }}
{{- end }}
