apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth.fullname" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
data:
  grpc_server_host: {{ printf "%s-%s.%s" .Release.Name .Values.global.users.nameOverride .Release.Namespace | quote }}
  grpc_server_port: {{ .Values.global.users.service.port | quote }}
