apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth.fullname" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "auth.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "auth.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-grpc-server
          image: busybox:latest
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for gRPC server to be ready..."
              echo "gRPC host: ${GRPC_HOST}"
              echo "gRPC port: ${GRPC_PORT}"
              until nc -z $GRPC_HOST $GRPC_PORT; do
                echo "gRPC server not ready, waiting 5 seconds..."
                sleep 5
              done
              echo "gRPC server is ready!"
          env:
            - name: GRPC_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "auth.fullname" . }}
                  key: grpc_server_host
            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "auth.fullname" . }}
                  key: grpc_server_port
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command:
            {{- range .Values.command }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.args }}
          args:
            {{- range .Values.args }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ include "auth.port" . }}
              protocol: TCP
          env: 
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth.fullname" . }}
                  key: jwt_secret_key
            - name: JWT_ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth.fullname" . }}
                  key: jwt_algorithm
            - name: JWT_ACCESS_EXPIRE
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth.fullname" . }}
                  key: jwt_expire
            - name: GRPC_SERVER_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth.fullname" . }}
                  key: grpc_server_address
            - name: LOG_DEBUG
              value: {{ .Values.debug | default .Values.global.debug | quote }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
