apiVersion: v1
kind: Secret
metadata:
  name: ingress-tls
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "tls/simplevod.crt" | b64enc }}
  tls.key: {{ .Files.Get "tls/simplevod.key" | b64enc }}
