nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

replicaCount: 1

image:
  repository: simplevod/upload
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []

command: []
args: []

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8200

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: upload.simplevod.app
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: ingress-tls
     hosts:
       - upload.simplevod.app

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health/liveness
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health/readiness
    port: http
  initialDelaySeconds: 15
  periodSeconds: 5
  timeoutSeconds: 10
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}
tolerations: []
affinity: {}

minio:
  endpoint: ""
  externalEndpoint: ""
  access_key: uploader
  secret_key: uploaderpassword
  bucket: raw
  use_ssl: false

mongodb:
  username: user
  password: password
  host: ""
  port: 27017
  database: upload

redis:
  host: ""
  port: 6379
  password: password
  db: 0
