apiVersion: v1
kind: Secret
metadata:
  name: {{ include "playlist.fullname" . }}
  labels:
    {{- include "playlist.labels" . | nindent 4 }}
data:
  minio_access_key: {{ .Values.minio.accessKey | b64enc }}
  minio_secret_key: {{ .Values.minio.secretKey | b64enc }}
  rabbitmq_user: {{ .Values.rabbitmq.user | b64enc }}
  rabbitmq_password: {{ .Values.rabbitmq.password | b64enc }}
  redis_password: {{ .Values.redis.password | b64enc }}
