apiVersion: v1
kind: Service
metadata:
  name: {{ include "playlist.fullname" . }}
  labels:
    {{- include "playlist.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.healthCheck.enabled }}
    - port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
      name: health
    {{- end }}
  selector:
    {{- include "playlist.selectorLabels" . | nindent 4 }}
