apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "users.fullname" . }}
  labels:
    {{- include "users.labels" . | nindent 4 }}
data:
  postgresql_host: {{ printf "%s-%s.%s" .Release.Name .Values.global.postgresql_users.nameOverride .Release.Namespace | quote }}
  postgresql_port: {{ .Values.global.postgresql_users.service.ports.postgresql | quote }}
  broker_host: {{ printf "%s-%s-master.%s" .Release.Name .Values.global.redis_users.nameOverride .Release.Namespace | quote }}
  broker_port: "6379"