apiVersion: v1
kind: Secret
metadata:
  name: {{ include "users.fullname" . }}
  labels:
    {{- include "users.labels" . | nindent 4 }}
type: Opaque
stringData:
  database_url: {{ printf "postgresql://%s:%s@%s:%d/%s" .Values.global.postgresql_users.auth.username .Values.global.postgresql_users.auth.password (printf "%s-%s.%s" .Release.Name .Values.global.postgresql_users.nameOverride .Release.Namespace) (int .Values.global.postgresql_users.service.ports.postgresql) .Values.global.postgresql_users.auth.database | quote }}
  celery_broker_url: {{ printf "redis://:%s@%s-%s-master.%s:6379/1" .Values.global.redis_users.redis.password .Release.Name .Values.global.redis_users.nameOverride .Release.Namespace| quote }}
  celery_backend_url: {{ printf "redis://:%s@%s-%s-master.%s:6379/2" .Values.global.redis_users.redis.password .Release.Name .Values.global.redis_users.nameOverride .Release.Namespace | quote }}
  email_server_name: {{ .Values.email.server | quote }}
  email_server_port: {{ .Values.email.port | quote }}
  email_address: {{ .Values.email.address | quote }}
  email_password: {{ .Values.email.password | quote }}
