apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-service
  labels:
    app: playlist-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: playlist-service
  template:
    metadata:
      labels:
        app: playlist-service
    spec:
      containers:
      - name: playlist-service
        image: playlist-service:latest
        ports:
        - containerPort: 8080
          name: health
        env:
        - name: HEALTH_PORT
          value: "8080"
        - name: REDIS_HOST
          value: "redis-service"
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: MINIO_ENDPOINT
          value: "minio-service:9000"
        
        # Kubernetes Health Checks
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        
        # Optional startup probe for slow-starting containers
        startupProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: playlist-service
spec:
  selector:
    app: playlist-service
  ports:
  - name: health
    port: 8080
    targetPort: 8080