apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finalizer.fullname" . }}
  labels:
    {{- include "finalizer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "finalizer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "finalizer.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "finalizer.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:latest
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for RabbitMQ to be ready..."
              until nc -z $RABBITMQ_HOST $RABBITMQ_PORT; do
                echo "RabbitMQ not ready, waiting 5 seconds..."
                sleep 5
              done
              echo "RabbitMQ is ready!"
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "finalizer.fullname" . }}
                  key: rabbitmq_host
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "finalizer.fullname" . }}
                  key: rabbitmq_port
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command:
            {{- range .Values.command }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.args }}
          args:
            {{- range .Values.args }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            {{- if .Values.healthCheck.enabled }}
            - name: health
              containerPort: {{ .Values.healthCheck.port }}
              protocol: TCP
            {{- end }}

          env: 
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "finalizer.fullname" . }}
                  key: minio_endpoint
            - name: MINIO_STREAM_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: {{ include "finalizer.fullname" . }}
                  key: minio_stream_bucket
            - name: MINIO_PUBLIC_HOSTNAME
              value: {{ .Values.minio.publicHostname | quote }}
            - name: MINIO_PUBLIC_SCHEME
              value: {{ .Values.minio.publicScheme | quote }}

            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "finalizer.fullname" . }}
                  key: mongo_url
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "finalizer.fullname" . }}
                  key: mongo_db_name

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "finalizer.fullname" . }}
                  key: redis_host
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "finalizer.fullname" . }}
                  key: redis_password
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "finalizer.fullname" . }}
                  key: redis_port
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "finalizer.fullname" . }}
                  key: redis_db

            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "finalizer.fullname" . }}
                  key: rabbitmq_host
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "finalizer.fullname" . }}
                  key: rabbitmq_port
            - name: RABBITMQ_VHOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "finalizer.fullname" . }}
                  key: rabbitmq_vhost
            - name: RABBITMQ_CONSUME_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "finalizer.fullname" . }}
                  key: rabbitmq_consume_queue
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "finalizer.fullname" . }}
                  key: rabbitmq_user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "finalizer.fullname" . }}
                  key: rabbitmq_password
            {{- if .Values.healthCheck.enabled }}
            - name: HEALTH_PORT
              value: {{ .Values.healthCheck.port | quote }}
            {{- end }}
            - name: LOG_DEBUG
              value: {{ .Values.debug | default .Values.global.debug | quote }}
          {{- if .Values.healthCheck.enabled }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
