apiVersion: v1
kind: Secret
metadata:
  name: {{ include "finalizer.fullname" . }}
  labels:
    {{- include "finalizer.labels" . | nindent 4 }}
data:
  mongo_url: {{ printf "mongodb://%s:%s@%s:%d" .Values.mongodb.username .Values.mongodb.password (printf "%s-%s.%s" .Release.Name .Values.global.mongodb.nameOverride .Release.Namespace) (int .Values.mongodb.port) | b64enc }}
  redis_password: {{ .Values.redis.password | b64enc }}
  rabbitmq_user: {{ .Values.rabbitmq.user | b64enc }}
  rabbitmq_password: {{ .Values.rabbitmq.password | b64enc }}
