apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iframebreaker.fullname" . }}
  labels:
    {{- include "iframebreaker.labels" . | nindent 4 }}
data:
  minio_access_key: {{ .Values.minio.accessKey | b64enc }}
  minio_secret_key: {{ .Values.minio.secretKey | b64enc }}
  rabbitmq_user: {{ .Values.rabbitmq.user | b64enc }}
  rabbitmq_password: {{ .Values.rabbitmq.password | b64enc }}
