apiVersion: v1
kind: Service
metadata:
  name: {{ include "users.fullname" . }}
  labels:
    {{- include "users.labels" . | nindent 4 }}
spec:
  type: {{ .Values.global.users.service.type | default .Values.grpcServer.service.type }}
  ports:
    - port: {{ include "users.port" . }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "users.selectorLabels" . | nindent 4 }}
