apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-mc" ( include "transcoder.fullname" . )}}
  labels:
    {{- include "transcoder.labels" . | nindent 4 }}
stringData:
  config.json: |
    {
      "version": "10",
      "aliases": {
        {{ .Values.minio.mcAlias | quote }}: {
          "url": {{ printf "http://%s" .Values.minio.endpoint | quote }},
          "accessKey": {{ .Values.minio.accessKey | quote }},
          "secretKey": {{ .Values.minio.secretKey | quote }},
          "api": "S3v2",
          "path": "dns"
        }
      }
    }
