apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-rabbitmqadmin" ( include "transcoder.fullname" . )}}
  labels:
    {{- include "transcoder.labels" . | nindent 4 }}
stringData:
  rabbitmqadmin.conf: |
    [transcode]
    hostname = {{ printf "%s-%s.%s" .Release.Name .Values.global.rabbitmq.nameOverride .Release.Namespace }}
    port = {{ .Values.rabbitmq.httpPort }}
    username = {{ .Values.rabbitmq.user }}
    password = {{ .Values.rabbitmq.password }}
    vhost = {{ .Values.rabbitmq.vhost }}
