{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "transcoder.fullname" . }}-role-binding
  labels:
    {{- include "transcoder.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "transcoder.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }} 
roleRef:
  kind: Role
  name: {{ include "transcoder.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
