apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "status.fullname" . }}
  labels:
    {{- include "status.labels" . | nindent 4 }}
data:
  mongo_host: {{ printf "%s-%s.%s" .Release.Name .Values.global.mongodb.nameOverride .Release.Namespace | quote }}
  mongo_port: {{ .Values.mongodb.port | quote }}
  mongo_db_name: {{ .Values.mongodb.database | quote }}

  rabbitmq_host: {{ printf "%s-%s.%s" .Release.Name .Values.global.rabbitmq.nameOverride .Release.Namespace | quote }}
  rabbitmq_port: {{ .Values.rabbitmq.port | quote }}
  rabbitmq_vhost: {{ .Values.rabbitmq.vhost | quote }}
  rabbitmq_consume_queue: {{ .Values.rabbitmq.queue | quote }}

  {{- if .Values.healthCheck.enabled }}
  health_port: {{ .Values.healthCheck.port | quote }}
  {{- end }}
