apiVersion: v1
kind: Secret
metadata:
  name: {{ include "status.fullname" . }}
  labels:
    {{- include "status.labels" . | nindent 4 }}
data:
  mongo_url: {{ printf "mongodb://%s:%s@%s:%d/%s?authSource=%s" .Values.mongodb.username .Values.mongodb.password (printf "%s-%s.%s" .Release.Name .Values.global.mongodb.nameOverride .Release.Namespace) (int .Values.mongodb.port) .Values.mongodb.database .Values.mongodb.authSource | b64enc }}
  rabbitmq_user: {{ .Values.rabbitmq.user | b64enc }}
  rabbitmq_password: {{ .Values.rabbitmq.password | b64enc }}
